apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: grpc-gateway-sample-oxmv
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: grpc-gateway-sample-oxmv
    app.kubernetes.io/part-of: grpc-gateway-sample
  name: grpc-gateway-sample-oxmv
spec:
  path: /
  port:
    targetPort: 3001
  to:
    kind: Service
    name: grpc-gateway-sample-oxmv
    weight: null
status: {}
